authors:
  team:
    name: Network Pro
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/170266279
    url: https://netwk.pro/
  SunDevil311:
    name: Scott Lopez
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/10506001
    url: https://github.com/SunDevil311
