authors:
  team:
    name: Network Pro
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/170266279
  SunDevil311:
    name: Scott Lopez
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/10506001
